# Generated by Django 4.2.7 on 2023-12-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobiasapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmittedLink',
            new_name='Link',
        ),
    ]
