# Generated by Django 5.0 on 2024-04-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobiasapp', '0002_rename_submittedlink_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
